language: ruby

before_script:
- sudo apt-get update -qq
- sudo apt-get install -y mtasc gnash
- mkdir -p bin vendor/flash
- git clone http://github.com/zorbfish/leanunit-actionscript2.git vendor/flash
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xfvb start"

script: bundle exec rake test
